<a href="https://colab.research.google.com/github/Kavitesh/projects/blob/main/pytorch/hello_world_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hello World in PyTorch

In [29]:
import torch

In [30]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [31]:
# Check number of dimensions
TENSOR.ndim

3

In [32]:
# Check shape
TENSOR.shape

torch.Size([1, 3, 3])

In [33]:
# Check shape by size()
TENSOR.size()

torch.Size([1, 3, 3])

In [34]:
# Check type
TENSOR.dtype

torch.int64

In [35]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [36]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [37]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [38]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [39]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [40]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# Add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# Multiply it by 10
tensor = torch.tensor([1, 2, 3])
tensor * 10

tensor([10, 20, 30])

In [43]:
# Subtract and reassign
tensor = torch.tensor([1, 2, 3])
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [47]:
# Original tensor is still unchanged, so reassign always
tensor = torch.tensor([1, 2, 3])
tensor + 10
tensor

tensor([1, 2, 3])

In [48]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [45]:
# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cpu


In [46]:
# Create a tensor and move it to device
hello_tensor = torch.tensor([1.0, 2.0, 3.0], device=device)
print("Hello, World from PyTorch!")
print("Tensor:", hello_tensor)

Hello, World from PyTorch!
Tensor: tensor([1., 2., 3.])
